name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  publish-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install build dependencies
        run: pip install .[dev]
      - name: Build package artifacts
        run: python -m build
      - name: Publish package artifacts to GitHub artifact registry
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: python -m twine upload --repository-url https://upload.pypi.pkg.github.com/${{ github.repository_owner }} dist/*
